# Connection detail is in K8S secret
db_connection_configs:
  - id: postgres_1
    type: postgres
    env_keys:
      host: OUTPUT_1_HOST
      port: OUTPUT_1_PORT
      username: OUTPUT_1_USERNAME
      password: OUTPUT_1_PASSWORD
      database: OUTPUT_1_DATABASE

schema_labels_mapping_configs:
  - id: mapping_1
    mapping:
      - query_label: instance
        table_column: instance
      - query_label: job
        table_column: job

output_configs:
  - id: output_1
    db_config:
      connections: postgres_1
      table: table_1
    mapping_config: mapping_1