promql_configs:
  - id: "node_cpu_usage_rate_10m"
    expr: 'rate(node_cpu_seconds_total{job="node-exporter", mode!="idle"}[10m])'
    export_labels:
      - "instance"

  - id: "node_cpu_usage_rate_120m"
    expr: 'rate(node_cpu_seconds_total{job="node-exporter", mode!="idle"}[120m])'
    export_labels:
      - "instance"

  - id: "node_memory_usage"
    expr: 'node_memory_Active_bytes{job="node_exporter"}'
    export_labels:
      - "instance"