cronjob_pipeline_export_file: "./sandbox_prometheus_query_pipeline.yaml"

config_files:
  file_path: "./"
  server_config: "test_server_config.yaml"
  promql_config: "test_promql_config.yaml"
  range_config: "test_range_config.yaml"

server_configs:
  - sandbox_prometheus

pipelines:
  - id: cpu_query_30d_4_5m
    metadata:
      cluster_name: sandbox_cluster
      environment: sandbox
    promql_config_id: node_cpu_usage
    range_config_id: 30d_4_5m

  - id: memory_query_30d_4_5m
    metadata:
      cluster_name: sandbox_cluster
      environment: sandbox
    promql_config_id: node_memory_usage
    range_config_id: 30d_4_5m

  - id: cpu_query_7d_4_1m
    metadata:
      cluster_name: sandbox_cluster
      environment: sandbox
    promql_config_id: node_cpu_usage
    range_config_id: 7d_4_1m

  - id: memory_query_7d_4_1m
    metadata:
      cluster_name: sandbox_cluster
      environment: sandbox
    promql_config_id: node_memory_usage
    range_config_id: 7d_4_1m