cronjob_pipeline_export_file: "./sandbox_prometheus_query_pipeline.yaml"

config_files:
  file_path: "./"
  server_config: "test_server_config.yaml"
  promql_config: "test_promql_config.yaml"
  range_config: "test_range_config.yaml"

server_configs:
  - sandbox_prometheus

pipelines:
  - id: node_cpu_rate_query_10m_windows_size
    metadata:
      cluster_name: sandbox_cluster
      environment: sandbox
    promql_config_ids: 
      - node_cpu_usage_rate_10m
    range_config_ids:
      - 7d_4_1m
      - 7d_4_5m

  - id: node_cpu_rate_query_120m_windows_size
    metadata:
      cluster_name: sandbox_cluster
      environment: sandbox
    promql_config_ids: 
      - node_cpu_usage_rate_120m
    range_config_ids:
      - 7d_4_30m
      - 7d_4_60m

  - id: node_memory_active_usage
    metadata:
      cluster_name: sandbox_cluster
      environment: sandbox
    promql_config_ids: 
      - node_memory_usage
    range_config_ids:
      - 7d_4_1m
      - 7d_4_5m
      - 7d_4_30m
      - 7d_4_60m